/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public final class ServiceId_s {

  public var serviceId: Int64

  public var serviceName: String

  public var serviceIp: String

  public var port: Int32


  public init(serviceId: Int64, serviceName: String, serviceIp: String, port: Int32) {
    self.serviceId = serviceId
    self.serviceName = serviceName
    self.serviceIp = serviceIp
    self.port = port
  }

}

public protocol EOG_Service {

  ///
  /// - Returns: ServiceId_s
  /// - Throws: EOG_Error
  func GetServiceId() throws -> ServiceId_s

  ///
  /// - Parameters:
  ///   - serviceId: 
  /// - Throws: EOG_Error
  func Heartbeat(serviceId: ServiceId_s) throws

  ///
  /// - Parameters:
  ///   - serviceId: 
  /// - Throws: EOG_Error
  func ClientConnected(serviceId: ServiceId_s) throws

  ///
  /// - Parameters:
  ///   - serviceId: 
  /// - Throws: EOG_Error
  func ClientAboutToDisconnect(serviceId: ServiceId_s) throws

  ///
  /// - Parameters:
  ///   - configName: 
  ///   - configuration: 
  /// - Throws: EOG_Error
  func ConfigurationChanged(configName: String, configuration: String) throws

}

open class EOG_ServiceClient : TClient /* , EOG_Service */ {

}

open class EOG_ServiceProcessor /* EOG_Service */ {

  typealias ProcessorHandlerDictionary = [String: (Int32, TProtocol, TProtocol, EOG_Service) throws -> Void]

  public var service: EOG_Service

  public required init(service: EOG_Service) {
    self.service = service
  }

}


