/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public final class EOG_Error : Swift.Error {

  public var errorCode: Int64

  public var errorMsg: String


  public init(errorCode: Int64, errorMsg: String) {
    self.errorCode = errorCode
    self.errorMsg = errorMsg
  }

}


