/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "eog_building_constants.h"

namespace riverfall { namespace eog {

const eog_buildingConstants g_eog_building_constants;

eog_buildingConstants::eog_buildingConstants() {
}

}} // namespace

