/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_exceptions_CONSTANTS_H
#define eog_exceptions_CONSTANTS_H

#include "eog_exceptions_types.h"

namespace riverfall { namespace eog {

class eog_exceptionsConstants {
 public:
  eog_exceptionsConstants();

};

extern const eog_exceptionsConstants g_eog_exceptions_constants;

}} // namespace

#endif
