/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_config_CONSTANTS_H
#define eog_config_CONSTANTS_H

#include "eog_config_types.h"

namespace riverfall { namespace eog {

class eog_configConstants {
 public:
  eog_configConstants();

};

extern const eog_configConstants g_eog_config_constants;

}} // namespace

#endif
