/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "eog_batsim_int_constants.h"

namespace riverfall { namespace eog {

const eog_batsim_intConstants g_eog_batsim_int_constants;

eog_batsim_intConstants::eog_batsim_intConstants() {
}

}} // namespace

