/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "eog_unit_constants.h"

namespace riverfall { namespace eog {

const eog_unitConstants g_eog_unit_constants;

eog_unitConstants::eog_unitConstants() {
}

}} // namespace

