/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_shared_CONSTANTS_H
#define eog_shared_CONSTANTS_H

#include "eog_shared_types.h"

namespace riverfall { namespace eog {

class eog_sharedConstants {
 public:
  eog_sharedConstants();

};

extern const eog_sharedConstants g_eog_shared_constants;

}} // namespace

#endif
