/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "eog_exceptions_constants.h"

namespace riverfall { namespace eog {

const eog_exceptionsConstants g_eog_exceptions_constants;

eog_exceptionsConstants::eog_exceptionsConstants() {
}

}} // namespace

