/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_unit_CONSTANTS_H
#define eog_unit_CONSTANTS_H

#include "eog_unit_types.h"

namespace riverfall { namespace eog {

class eog_unitConstants {
 public:
  eog_unitConstants();

};

extern const eog_unitConstants g_eog_unit_constants;

}} // namespace

#endif
