/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "eog_config_constants.h"

namespace riverfall { namespace eog {

const eog_configConstants g_eog_config_constants;

eog_configConstants::eog_configConstants() {
}

}} // namespace

