/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_building_CONSTANTS_H
#define eog_building_CONSTANTS_H

#include "eog_building_types.h"

namespace riverfall { namespace eog {

class eog_buildingConstants {
 public:
  eog_buildingConstants();

};

extern const eog_buildingConstants g_eog_building_constants;

}} // namespace

#endif
