/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_batsim_int_CONSTANTS_H
#define eog_batsim_int_CONSTANTS_H

#include "eog_batsim_int_types.h"

namespace riverfall { namespace eog {

class eog_batsim_intConstants {
 public:
  eog_batsim_intConstants();

};

extern const eog_batsim_intConstants g_eog_batsim_int_constants;

}} // namespace

#endif
