/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "eog_config_types_constants.h"

namespace riverfall { namespace eog {

const eog_config_typesConstants g_eog_config_types_constants;

eog_config_typesConstants::eog_config_typesConstants() {
}

}} // namespace

