/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef eog_config_types_CONSTANTS_H
#define eog_config_types_CONSTANTS_H

#include "eog_config_types_types.h"

namespace riverfall { namespace eog {

class eog_config_typesConstants {
 public:
  eog_config_typesConstants();

};

extern const eog_config_typesConstants g_eog_config_types_constants;

}} // namespace

#endif
